-- Colleague names were fictional characters (Batman, Bilbo, Bugs Bunny...), which belong to someone.
-- They become ordinary first names, one for one with the same initial, so teams keep their letter;
-- within a letter no two share their first two letters, for a two-letter avatar.
CREATE OR REPLACE FUNCTION colleague_name(ordinal BIGINT) RETURNS TEXT
LANGUAGE SQL IMMUTABLE STRICT AS $$
  SELECT (ARRAY[
    'Ada', 'Bea', 'Cleo', 'Dara', 'Elif', 'Farah', 'Gaia', 'Hana', 'Ida', 'Jade', 'Kai', 'Lars', 'Maya', 'Nadia', 'Oona', 'Paz', 'Quinn', 'Rafa', 'Sami', 'Tara', 'Uma', 'Vera', 'Wren', 'Xavi', 'Yara', 'Zara'
  ])[((ordinal - 1) % 26 + 1)::INTEGER]
  || CASE WHEN ordinal > 26 THEN ' ' || ((ordinal - 1) / 26 + 1)::TEXT ELSE '' END
$$;

WITH mapping(old_name, new_name) AS (VALUES
    ('Alice', 'Ada'),
    ('Aragorn', 'Arlo'),
    ('Aang', 'Amira'),
    ('Ariel', 'Alba'),
    ('Anakin', 'Avery'),
    ('Bart', 'Bea'),
    ('Batman', 'Bodhi'),
    ('Bilbo', 'Bruno'),
    ('Buffy', 'Blair'),
    ('Bugs Bunny', 'Bianca'),
    ('Coraline', 'Cleo'),
    ('Charlie Brown', 'Cora'),
    ('Chewbacca', 'Cyrus'),
    ('Cinderella', 'Chiara'),
    ('Chihiro', 'Caleb'),
    ('Daria', 'Dara'),
    ('Dobby', 'Devi'),
    ('Daphne', 'Diego'),
    ('Dexter', 'Drew'),
    ('Daenerys', 'Dylan'),
    ('Elsa', 'Elif'),
    ('Elmo', 'Emeka'),
    ('Eowyn', 'Esra'),
    ('Eeyore', 'Ezra'),
    ('Edna Mode', 'Evan'),
    ('Frodo', 'Farah'),
    ('Fiona', 'Felix'),
    ('Fry', 'Finn'),
    ('Fred Flintstone', 'Flora'),
    ('Fozzie', 'Freya'),
    ('Gandalf', 'Gaia'),
    ('Garfield', 'Gemma'),
    ('Groot', 'Gina'),
    ('Goku', 'Greta'),
    ('Gon', 'Gus'),
    ('Hannah Montana', 'Hana'),
    ('Hermione', 'Hector'),
    ('Homer', 'Hiro'),
    ('Hiccup', 'Hollis'),
    ('Heidi', 'Hugo'),
    ('Ichabod Crane', 'Ida'),
    ('Indiana Jones', 'Ilya'),
    ('Inigo Montoya', 'Imani'),
    ('Iroh', 'Ines'),
    ('Iron Man', 'Isla'),
    ('Jessie', 'Jade'),
    ('Jasmine', 'Jens'),
    ('Jinx', 'Jiro'),
    ('Jiminy Cricket', 'Jonah'),
    ('Jack Sparrow', 'Jude'),
    ('Katniss', 'Kai'),
    ('Kiki', 'Kenji'),
    ('Kermit', 'Kira'),
    ('Korra', 'Kofi'),
    ('Kirby', 'Kyra'),
    ('Lilo', 'Lars'),
    ('Leia', 'Leni'),
    ('Luigi', 'Lina'),
    ('Luna Lovegood', 'Lorenzo'),
    ('Legolas', 'Lucia'),
    ('Matilda', 'Maya'),
    ('Mulan', 'Meera'),
    ('Mario', 'Milo'),
    ('Moana', 'Mona'),
    ('Mowgli', 'Musa'),
    ('Nemo', 'Nadia'),
    ('Naruto', 'Neil'),
    ('Nala', 'Nico'),
    ('Ned Flanders', 'Noor'),
    ('Neville', 'Nuri'),
    ('Obi-Wan', 'Oona'),
    ('Olaf', 'Olu'),
    ('Obelix', 'Omar'),
    ('Odie', 'Orla'),
    ('Oswald', 'Otis'),
    ('Paddington', 'Paz'),
    ('Pikachu', 'Petra'),
    ('Popeye', 'Pia'),
    ('Pippin', 'Polly'),
    ('Peter Pan', 'Priya'),
    ('Quasimodo', 'Quinn'),
    ('Quark', 'Qi'),
    ('Qui-Gon Jinn', 'Qasim'),
    ('Quint', 'Qodir'),
    ('Quentin Coldwater', 'Qendresa'),
    ('Rapunzel', 'Rafa'),
    ('Ron Weasley', 'Remi'),
    ('R2-D2', 'Rio'),
    ('Robin Hood', 'Rosa'),
    ('Remy', 'Ruth'),
    ('Scooby-Doo', 'Sami'),
    ('Sonic', 'Selin'),
    ('Shrek', 'Sinead'),
    ('Snoopy', 'Sofia'),
    ('Samwise', 'Sunil'),
    ('Totoro', 'Tara'),
    ('Tintin', 'Teo'),
    ('Tigger', 'Tilda'),
    ('Tiana', 'Tomas'),
    ('Toothless', 'Tuva'),
    ('Ursula', 'Uma'),
    ('Uhura', 'Uri'),
    ('Usagi', 'Ulla'),
    ('Uhtred', 'Una'),
    ('Ultron', 'Ugo'),
    ('Velma', 'Vera'),
    ('Violet Parr', 'Vik'),
    ('Vash', 'Valentin'),
    ('Vegeta', 'Vlasta'),
    ('Vivi', 'Vy'),
    ('Winnie the Pooh', 'Wren'),
    ('Wall-E', 'Wanda'),
    ('Wendy Darling', 'Willa'),
    ('Woody', 'Wes'),
    ('Willy Wonka', 'Wojtek'),
    ('Xena', 'Xavi'),
    ('Xander Harris', 'Ximena'),
    ('Xion', 'Xenia'),
    ('Xavier', 'Xochitl'),
    ('Xerxes', 'Xuan'),
    ('Yoda', 'Yara'),
    ('Yoshi', 'Yemi'),
    ('Yugi', 'Yiannis'),
    ('Yennefer', 'Yosef'),
    ('Yor', 'Yusuf'),
    ('Zelda', 'Zara'),
    ('Zuko', 'Zeno'),
    ('Zorro', 'Zia'),
    ('Zazu', 'Zoltan'),
    ('Zoidberg', 'Zuri')
), staff AS (
  SELECT a.id, a.display AS old_display,
         m.new_name || substring(a.display FROM length(m.old_name) + 1) AS new_display
  FROM actors a
  JOIN mapping m ON a.display = m.old_name OR a.display LIKE m.old_name || ' %'
  WHERE a.kind = 'staff'
    AND (a.display = m.old_name OR substring(a.display FROM length(m.old_name) + 2) ~ '^[0-9]+$')
), renamed AS (
  UPDATE actors a SET display = s.new_display FROM staff s WHERE a.id = s.id
  RETURNING a.id, s.old_display, a.display
)
INSERT INTO events (kind, actor_id, body)
SELECT 'actor_display_changed', id,
       jsonb_build_object('actor_id', id, 'from_display', old_display, 'to_display', display,
                          'reason', 'Colleagues have ordinary names, never fictional characters')
FROM renamed;
