import { mkdir, rm, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';

const out = 'dist';
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

const nav = [
  ['/product/', 'Product'], ['/how-it-works/', 'How it works'], ['/research/', 'Research'],
  ['/compare/', 'Compare'], ['/journal/', 'Journal']
];
const findings = [
  {slug:'one-worker-default', n:'01', title:'One strong worker is the default', dek:'Inside one tightly coupled outcome, coordination has to earn its cost.', stat:'1 → 1', label:'lead to Staff, by default'},
  {slug:'parallel-thresholds', n:'02', title:'Parallelism has a demand shape', dek:'A large queue can reward more workers. A slow arrival stream often cannot.', stat:'1.9×', label:'throughput in one monitoring arm'},
  {slug:'supervision-correctness', n:'03', title:'Presence is not correctness', dek:'Available supervision prevented stale work, then introduced a defect of its own.', stat:'96 / 96', label:'cases closed, with one contamination'}
];

function linkNav(current) {
  return nav.map(([href,label]) => `<a href="${href}"${current===href?' aria-current="page"':''}>${label}</a>`).join('');
}
function layout({title, desc, route, body, cls=''}) {
  const url = `https://restless.example${route}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Restless</title><meta name="description" content="${desc}"><meta name="theme-color" content="#f0efe9"><meta property="og:title" content="${title} | Restless"><meta property="og:description" content="${desc}"><meta property="og:type" content="website"><meta property="og:url" content="${url}"><meta property="og:image" content="https://restless.example/social-card.svg"><meta name="twitter:card" content="summary_large_image"><link rel="canonical" href="${url}"><link rel="icon" href="/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script type="module" src="/assets/site.js"></script></head><body class="${cls}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Restless home"><span class="brand-mark" aria-hidden="true">R/</span>Restless</a><button class="menu" aria-expanded="false" aria-controls="nav">Menu</button><nav id="nav" aria-label="Primary">${linkNav(route)}</nav><a class="signal" href="/research/">Research stage <span aria-hidden="true">↗</span></a></header><main id="main">${body}</main><footer><div class="foot-brand">R/</div><div><strong>Restless</strong><p>A research programme for companies that handle work.</p></div><nav aria-label="Footer">${linkNav(route)}</nav><p class="fine">Research-stage product direction. No claim of general availability.</p></footer></body></html>`;
}
const arrow = '<span aria-hidden="true">↗</span>';
const cta = (href,text) => `<a class="arrow-link" href="${href}">${text} ${arrow}</a>`;
const pageHead = (kicker,title,lead) => `<header class="page-head"><p class="index">${kicker}</p><h1>${title}</h1><p class="lede">${lead}</p></header>`;

const home = `
<section class="hero"><div class="hero-copy"><p class="status"><i></i> An active research direction</p><h1>Your company<br><em>keeps going.</em></h1><p class="hero-lede">Give it the mission. Restless organises the work, supervises the outcome and returns with the prepared decisions that are genuinely yours.</p><div class="actions">${cta('/product/','See the owner experience')}${cta('/research/','Inspect the evidence')}</div></div>
<div class="handoff" data-demo><div class="handoff-top"><span>Owner attention / 08:42</span><span class="live">Prepared for judgement</span></div><div class="mission"><span>Your instruction</span><strong data-mission>Find the weakest part of our launch plan and repair what can be repaired.</strong></div><ol class="workline" aria-label="Example company progress"><li><b>Framed</b><span>Launch readiness has one accountable owner</span></li><li><b>Produced</b><span>Evidence checked across plan, budget and live build</span></li><li><b>Repaired</b><span>Broken onboarding path fixed and re-tested</span></li></ol><div class="decision"><span>Only you can decide</span><strong>Keep Friday’s date with a smaller first cohort?</strong><div class="decision-actions"><button data-choice="yes">Keep date</button><button data-choice="later">See trade-offs</button></div><p data-result aria-live="polite">Everything around this decision is prepared. Nothing consequential has been sent.</p></div><div class="demo-pick" aria-label="Change example"><button class="active" data-example="launch">Launch</button><button data-example="research">Research</button><button data-example="operations">Operations</button></div></div></section>
<section class="attention"><p class="index">The attention exchange</p><h2>Work leaves your desk.<br><em>Judgement comes back.</em></h2><div class="exchange"><div><span>01</span><h3>You set direction</h3><p>Mission, priorities, limits and taste. Not a flowchart of every step.</p></div><div><span>02</span><h3>The company handles work</h3><p>It delegates real production, watches the outcome and repairs through accountable people.</p></div><div><span>03</span><h3>You get the last mile</h3><p>A live result, the exact decision and the prepared state needed to act.</p></div></div></section>
<section class="proof-band"><div><p class="index">Built around outcomes</p><h2>Not another place to manage agents.</h2></div><p>Files hold the work. Git marks meaningful checkpoints. Native artifacts make results judgeable. Deterministic boundaries keep authority, money and external effects out of model discretion.</p>${cta('/how-it-works/','Follow one outcome')}</section>
<section class="research-cut"><p class="index">Field notes, not folklore</p><h2>We publish what changed our mind.</h2><div class="finding-row">${findings.map(f=>`<a href="/journal/${f.slug}/"><span>${f.n}</span><h3>${f.title}</h3><p>${f.dek}</p>${arrow}</a>`).join('')}</div></section>`;

const product = `${pageHead('Product / owner experience','Bring the mission.<br>Not the machinery.','Restless is intended to feel like appointing a capable company, not configuring an agent framework. The owner remains the source of direction, limits and judgement.')}
<section class="split"><div><p class="index">What changes</p><h2>Your working day has fewer open loops.</h2></div><div class="prose"><p>You ask for an outcome once. A singleton Exec places it with one accountable lead. Staff does the machine-doable work. The lead stays available to notice drift, redirect production and judge the exact result.</p><p>The return is not a cheerful summary. It is the native artifact, supporting evidence, and a bounded decision if one remains.</p></div></section>
<section class="last-mile"><div><p class="index">The prepared last mile</p><h2>Restless stops at the line only you can cross.</h2><p>Identity, sign-in, CAPTCHA, two-factor authentication, legal attestation, payment confirmation and irreducible taste stay with you. The surrounding workflow does not.</p></div><div class="receipt"><span>Prepared owner action</span><h3>Approve the final production order</h3><dl><div><dt>Already done</dt><dd>Supplier terms compared, quantities checked, draft order preserved</dd></div><div><dt>Your act</dt><dd>Legal acceptance and payment confirmation</dd></div><div><dt>Resume signal</dt><dd>Provider order state observed</dd></div></dl><button disabled>Owner identity required</button></div></section>
<section class="boundary"><p class="index">Product boundary</p><h2>The target is a company control plane.</h2><div class="boundary-grid"><div><strong>It is for</strong><p>Useful economic output per unit of owner attention, time, cost and bounded risk.</p></div><div><strong>It is not primarily</strong><p>A chat assistant, agent builder, workflow canvas, task tracker or audit product.</p></div><div><strong>Current maturity</strong><p>A clean-slate research programme with explicit architecture and controlled dogfood, not claimed general availability.</p></div></div>${cta('/research/','See what is proven and provisional')}</section>`;

const how = `${pageHead('System / one outcome','Accountability<br>without ceremony.','A sparse organisation gives each outcome one owner, gives production a real worker, and keeps the Exec free for what comes next.')}
<section class="org"><div class="org-row exec"><span>01</span><div><h2>Exec</h2><p>Owns the portfolio. Delegates every executable request to exactly one lead, then returns to availability.</p></div></div><div class="org-row lead"><span>02</span><div><h2>Accountable lead</h2><p>Owns one coherent outcome. Supervises rather than produces. Frames, observes, redirects, repairs and judges.</p></div></div><div class="org-row staff"><span>03</span><div><h2>Staff</h2><p>Produces the actual work. One strong end-to-end worker is the default until another stable seam earns its coordination cost.</p></div></div><div class="org-row owner"><span>04</span><div><h2>Owner</h2><p>Receives the live outcome and the prepared judgement call, not the organisation’s internal traffic.</p></div></div></section>
<section class="kernel"><div><p class="index">Three logical layers</p><h2>Judgement above.<br>Rules at the boundary.<br>Work in the world.</h2></div><ol><li><b>Constitutional Kernel</b><p>Deterministic authority, identity, secrets, budgets, consequential effects and recovery.</p></li><li><b>Organisational Intelligence</b><p>Goals, actors, sparse Work, Attempts, messages and repair. Recoverable and overridable.</p></li><li><b>Company Linux Runtime</b><p>Persistent files, Git, browsers and ordinary tools where outcomes are made.</p></li></ol></section>
<section class="native"><p class="index">Outcome-native review</p><h2>Review the thing itself.</h2><p>A live site, playable build, rendered document, image or executable scenario comes first. Commits, tests and receipts support the judgement. They do not replace it.</p>${cta('/journal/supervision-correctness/','Read why supervision still needs checks')}</section>`;

const research = `${pageHead('Research / public notebook','A theory that has<br>to survive contact.','Restless separates enduring product decisions from provisional beliefs, open hypotheses and implementation defects. Experiments are allowed to change the organisation.')}
<section class="maturity"><article><span>Accepted direction</span><h2>Enduring</h2><ul><li>Deterministic rules own authority and consequential effects.</li><li>Files are the primary work primitive.</li><li>Every executable outcome has an accountable lead and real Staff production.</li><li>Review arrives in the outcome’s native form.</li></ul></article><article><span>Supported, not universal</span><h2>Provisional</h2><ul><li>One end-to-end worker is the best default inside a coherent outcome.</li><li>Parallel capacity pays when work arrives as independent, locally closing units.</li><li>Natural supervision over sparse facts beats forced coordination ritual.</li></ul></article><article><span>Still to learn</span><h2>Open</h2><ul><li>What signal predicts context saturation?</li><li>When does a parallel hand become Staff?</li><li>Which artifact boundaries generalise beyond code?</li><li>Can inbound signals preserve authority and owner attention?</li></ul></article></section>
<section class="method"><p class="index">Method</p><h2>Observation before fact.</h2><div class="method-line"><div><b>Claim</b><p>Someone or something asserts it.</p></div><i></i><div><b>Observation</b><p>A method records what happened.</p></div><i></i><div><b>Evidence</b><p>Material supports or challenges it.</p></div><i></i><div><b>Accepted fact</b><p>The company decides what to act on.</p></div></div><p class="note">Controlled dogfood can test a mechanism. It cannot establish customer demand, broad reliability or real-world commercial performance.</p></section>
<section class="open-q"><h2>Useful questions remain open.</h2><p>That is the point of publishing the notebook rather than manufacturing certainty.</p>${cta('/journal/','Read current findings')}</section>`;

const compare = `${pageHead('Category view / observed 26 August 2026','Close neighbours.<br>Different centres.','A source-first comparison of public materials. Product descriptions are observations from the linked sources. The differentiation is our interpretation, not a benchmark verdict.')}
<section class="compare-table" aria-label="Category comparison"><div class="compare-row headings"><span>Product</span><span>What its source presents</span><span>Centre of gravity</span></div><div class="compare-row"><h2>opencompany</h2><p>Its public site calls it a multiplayer AI workspace with a self-building wiki, workflows, model-agnostic sessions, connected sources and cloud sandboxes.</p><p><b>Observed centre:</b> a shared workspace where humans and agents run company processes.</p><a href="https://www.opencompany.cloud/">Primary site ${arrow}</a></div><div class="compare-row"><h2>Lindy</h2><p>Its public site presents an “AI teammate” that connects to company tools, knows company context and does work for a team. It visibly promotes integrations and a hosted sign-up.</p><p><b>Observed centre:</b> tool-connected AI teammates and automation for business functions.</p><a href="https://www.lindy.ai/">Primary site ${arrow}</a></div><div class="compare-row"><h2>CrewAI</h2><p>Its documentation describes an open-source framework that combines structured, event-driven Flows with autonomous agent Crews.</p><p><b>Observed centre:</b> developer orchestration of multi-agent applications and workflows.</p><a href="https://docs.crewai.com/en/introduction">Primary docs ${arrow}</a></div><div class="compare-row restless-row"><h2>Restless</h2><p>Our intended product is a control plane for owner/operators. It delegates outcomes through accountable leads, real Staff production and a persistent runtime.</p><p><b>Intended centre:</b> useful company output per unit of scarce owner attention.</p><a href="/product/">Product boundary ${arrow}</a></div></section>
<section class="interpret"><div><p class="index">Our interpretation</p><h2>The difference is where the owner stands.</h2></div><div><p>Restless is not centred on a workspace to inhabit, a set of AI teammates to configure, or a framework to build. It is centred on delegating a whole outcome and receiving the prepared last mile.</p><p>This comparison does not establish relative quality, availability or fit. We did not run these products in a common benchmark. Public materials can change after the observation date.</p></div></section>`;

const journal = `${pageHead('Journal / current findings','What changed<br>our operating theory.','Durable notes from controlled coordination work. Each finding keeps its limits attached.')}
<section class="journal-list">${findings.map(f=>`<a href="/journal/${f.slug}/"><span class="journal-num">${f.n}</span><div><h2>${f.title}</h2><p>${f.dek}</p></div><div class="journal-stat"><strong>${f.stat}</strong><small>${f.label}</small></div>${arrow}</a>`).join('')}</section><section class="journal-note"><p>These findings come from controlled programmes. They refine a product theory. They do not prove broad customer outcomes or general availability.</p>${cta('/research/','See the research method')}</section>`;

const articleBodies = {
'one-worker-default': `<p class="standfirst">More autonomous minds look like more capacity. Inside one tightly coupled outcome, they can instead create more surfaces to brief, synchronise, integrate and review.</p><h2>What we observed</h2><p>Several controlled arrangements compared a strong end-to-end worker with specialist chains or multi-worker assemblies. On complete-outcome economics, the one-worker shape often won. Decomposability was necessary but not sufficient. A seam also had to produce independently valuable evidence or expertise.</p><blockquote><strong>The exception matters.</strong><p>One sequential two-specialist marketing chain won blind quality. Two-operator-plus-assembler sales and three-worker research arrangements lost.</p></blockquote><h2>What changed</h2><p>The organisation now starts wide and shallow: one accountable lead with one Staff producer. Another worker is added only when a stable specialism, independent evidence, local closure or context limit can repay the coordination cost.</p><h2>What this does not prove</h2><p>It is not a universal solo-agent rule. It does not show that one worker wins every domain, scale or model mix. It establishes a default that must be displaced by evidence, not headcount optimism.</p>`,
'parallel-thresholds': `<p class="standfirst">“How much work?” is the wrong first question. The useful question is whether units are simultaneously available, independent and able to close locally.</p><h2>Two demand shapes</h2><p>With 240 sales accounts available at once, two workers crossed the throughput threshold twice. When the same population arrived gradually, extra workers did not improve p90 response time. Four workers were faster in one arm, but marginal tail quality weakened.</p><div class="data-pair"><div><strong>240</strong><span>accounts simultaneously available</span></div><div><strong>≠</strong><span>the same accounts arriving gradually</span></div></div><h2>A second workload</h2><p>An independent monitoring workload crossed at 40 entities. Two workers delivered about 1.9 times throughput and 0.55 times p90 latency, with lower charged cost per alert. Worst-unit consistency fell by 1.5 points.</p><h2>What changed</h2><p>Capacity is now matched to ready independent units, not department name or total task count. Quality at the worst unit remains part of the decision. This is a provisional threshold pattern, not a universal scaling law.</p>`,
'supervision-correctness': `<p class="standfirst">A lead must remain available to preserve the mission. Availability improves recovery. It does not make the lead infallible.</p><h2>What we observed</h2><p>In a support experiment, causal policy delivery prevented 16 stale outcomes and closed 96 of 96 cases. A terminal-only comparison accepted 80 of 96.</p><div class="data-pair"><div><strong>16</strong><span>stale outcomes prevented</span></div><div><strong>1</strong><span>duplicate-case contamination introduced</span></div></div><p>The supervised run created its own defect. Independent evaluation caught one duplicate-case contamination. The same mechanism that improved recovery did not guarantee correctness.</p><h2>What changed</h2><p>The lead remains a distinct, non-producing mission keeper and final judge, even when that adds latency. Consequential acceptance boundaries still need independent outcome checks. Supervision can escalate a concern. It cannot grant itself authority.</p><h2>What remains open</h2><p>We still need to learn which checks best generalise across code, research, documents and live operations without turning judgement into a rigid workflow.</p>`
};
function article(f) { return `${pageHead(`Finding ${f.n} / coordination`,f.title,f.dek)}<article class="article"><div class="article-meta"><span>Research note</span><span>Evidence pack / current programme</span><span>Qualification preserved</span></div>${articleBodies[f.slug]}<nav class="article-next" aria-label="Finding navigation"><a href="/journal/">All findings ${arrow}</a><a href="/research/">Research method ${arrow}</a></nav></article>`; }

const pages = [
 ['index.html', layout({title:'A company that keeps going',desc:'Restless handles company work and returns the prepared decisions only the owner can make.',route:'/',body:home,cls:'home'})],
 ['product/index.html',layout({title:'The owner experience',desc:'Bring the mission, not the machinery. See the product boundary and prepared last mile.',route:'/product/',body:product})],
 ['how-it-works/index.html',layout({title:'How accountability works',desc:'Exec, accountable leads and Staff turn a mission into a native outcome.',route:'/how-it-works/',body:how})],
 ['research/index.html',layout({title:'Research notebook',desc:'Accepted directions, provisional beliefs and open questions in the Restless research programme.',route:'/research/',body:research})],
 ['compare/index.html',layout({title:'Category comparison',desc:'A dated, sourced comparison of Restless with adjacent products and frameworks.',route:'/compare/',body:compare})],
 ['journal/index.html',layout({title:'Research journal',desc:'Findings from controlled work on delegation, capacity and supervision.',route:'/journal/',body:journal})],
 ...findings.map(f=>[`journal/${f.slug}/index.html`,layout({title:f.title,desc:f.dek,route:`/journal/${f.slug}/`,body:article(f)})])
];
for (const [file, html] of pages) { const target=path.join(out,file); await mkdir(path.dirname(target),{recursive:true}); await writeFile(target,html); }
await mkdir(path.join(out,'assets'),{recursive:true});
await cp('src/site.css',path.join(out,'assets/site.css'));
await cp('src/site.js',path.join(out,'assets/site.js'));
await cp('src/mark.svg',path.join(out,'mark.svg'));
await cp('src/social-card.svg',path.join(out,'social-card.svg'));
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\n');
console.log(`Built ${pages.length} routes into ${out}/`);
